data:
  filepath: /Users/cjesus/Documents/HKnuTomo/config/full.PREM.dat
  save_new: True

output:
  outdir: /Users/cjesus/Documents/HKnuTomo/output
  osc-outdir: /Users/cjesus/Documents/HKnuTomo/output/osc

earth:
  layers:
    - center
    - IC
    - OC
    - MT
    - CR
  IC_R: 1221.5
  OC_R: 3480
  MT_R: 6336
  CR_R: 6372

dial:
  kappa: -0.0
  IC_upper_limit: 100.
  var_rhos: 500
  check_thre: 0.001
  deltaR:
    - 0
    - 0
    - 0.0
    - 0.0

osc3:
  oscpar:
    t12: 0.308
    t13: 0.0220
    t23: 0.45
    m21: 7.54e-5
    mAtm: 2.40e-3
    delta: -1.75
  zenith:
    cosz: -1.0
  # ks: 0 - sin2(2q) variables
  # ks: 1 - sin2( q) variables
  ks: 1
  # nutype:  1 - neutrino
  # nutype: -1 - antineutrino
  nutype: 1
  # neutrino flavor: 1: electron. 2: muon. 3: tau
  nu_origin: 2
  nu_end: 1
  Enu_min: 1.
  Enu_max: 21.
  prod_height: 20.